name: Close stale issues and PRs
on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: "This issue is stale because it has been open 1 year with no activity. Remove the stale label or add a comment, otherwise this will be closed in 30 days."
          stale-pr-message: "This PR is stale because it has been open 1 year with no activity. Remove the stale label or add a comment, otherwise this will be closed in 30 days."
          close-issue-message: "This issue was closed because it has been stale for 1 year with no activity."
          close-pr-message: "This PR was closed because it has been stale for 1 year with no activity."
          days-before-issue-stale: 365
          days-before-pr-stale: 365
          days-before-issue-close: 30
          days-before-pr-close: 30
          stale-issue-label: "stale"
          stale-pr-label: "stale"
